name: Fetch Steelers Depth Chart

# Run manually only
on:
  workflow_dispatch:

jobs:
  fetch-depth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd fetchimages
          npm install

      - name: Run depth chart fetch
        run: |
          cd fetchimages
          node depth.js

      - name: Commit and push depth.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add fetchimages/depth.json
          git commit -m "Update depth chart"
          git push
        # Only commit if there are changes
        continue-on-error: true