name: Run Steelers Scripts Sequentially

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-sequential-scripts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies from package.json (no lockfile needed)
      - name: Install dependencies
        run: npm install

      # Step 4: Run scripts sequentially
      - name: Run scripts sequentially
        run: node run-scripts.js