name: Data Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # adjust schedule if needed

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      ####################################
      # Checkout repo
      ####################################
      - name: Checkout repo
        uses: actions/checkout@v4

      ####################################
      # 1. fetch-steelers.js
      ####################################
      - name: Install dependencies for fetch-steelers.js
        run: |
          echo ">>> Installing dependencies in fetch/"
          cd fetch
          npm install
          cd -
      
      - name: Run fetch-steelers.js
        run: |
          echo ">>> Running fetch/fetch-steelers.js"
          node fetch/fetch-steelers.js
          echo ">>> Git status before commit:"
          git status -s
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fetch/rosterupdate.json
          git commit -m "Update rosterupdate.json" || echo "No changes to commit"
          git push
          echo ">>> Git status after commit:"
          git status -s

      ####################################
      # 2. images-fetch-steelers.js
      ####################################
      - name: Install dependencies for images-fetch-steelers.js
        run: |
          echo ">>> Installing dependencies in fetchimages/"
          cd fetchimages
          npm install
          cd -

      - name: Run images-fetch-steelers.js
        run: |
          echo ">>> Running fetchimages/images-fetch-steelers.js"
          node fetchimages/images-fetch-steelers.js
          echo ">>> Git status before commit:"
          git status -s
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fetchimages/images-rosterupdate.json
          git add fetchimages/images/
          git commit -m "Update images-rosterupdate.json and images" || echo "No changes to commit"
          git push
          echo ">>> Git status after commit:"
          git status -s

      ####################################
      # 3. trivia.js
      ####################################
      - name: Install dependencies for trivia.js
        run: |
          echo ">>> Installing dependencies in fetchimages/"
          cd fetchimages
          npm install
          cd -

      - name: Run trivia.js
        run: |
          echo ">>> Running fetchimages/trivia.js"
          node fetchimages/trivia.js
          echo ">>> Git status before commit:"
          git status -s
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fetchimages/trivia.json
          git commit -m "Update trivia.json" || echo "No changes to commit"
          git push
          echo ">>> Git status after commit:"
          git status -s

      ####################################
      # 4. depth.js
      ####################################
      - name: Install dependencies for depth.js
        run: |
          echo ">>> Installing dependencies in fetchimages/"
          cd fetchimages
          npm install
          cd -

      - name: Run depth.js
        run: |
          echo ">>> Running fetchimages/depth.js"
          node fetchimages/depth.js
          echo ">>> Git status before commit:"
          git status -s
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add fetchimages/depth.json
          git commit -m "Update depth.json" || echo "No changes to commit"
          git push
          echo ">>> Git status after commit:"
          git status -s