name: Trivia Shuffle

on:
  workflow_dispatch:  # run manually for testing

jobs:
  shuffle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # required for commits

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd fetchimages
          npm install

      - name: Run trivia-shuffle
        run: |
          cd fetchimages
          node -e "import { generateTriviaParagraph } from './trivia-shuffle.js';
          import fs from 'fs';
          const inputFile = 'temp.json';
          const outputFile = 'tempoutput.json';
          if (!fs.existsSync(inputFile)) {
            console.error('temp.json not found');
            process.exit(1);
          }
          const inputIds = JSON.parse(fs.readFileSync(inputFile, 'utf-8'));
          const output = {};
          for (const pid of inputIds) {
            output[pid] = generateTriviaParagraph(pid);
          }
          fs.writeFileSync(outputFile, JSON.stringify(output, null, 2));
          console.log('Output written to', outputFile);"

      - name: Commit tempoutput.json
        run: |
          cd fetchimages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tempoutput.json
          git diff --cached --quiet || git commit -m "Update tempoutput.json via trivia-shuffle"
          git push