name: Update Steelers Roster

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  fetch-roster:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        working-directory: ./fetch
        run: npm install

      # 4️⃣ Run the fetch script
      - name: Run fetch-steelers.js
        working-directory: ./fetch
        run: node fetch-steelers.js

      # 5️⃣ Commit and push the updated JSON
      - name: Commit & Push rosterupdate.json
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main              # Target branch
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Built-in token
          directory: ./fetch        # Only commit this folder
          commit_message: "Update Steelers roster [skip ci]"
          force: true