name: Roster Fetch

on:
  workflow_dispatch: # Manual trigger only

jobs:
  fetch-roster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run roster fetch
        run: node roster-fetch.js