name: Roster Fetch

# Trigger only manually
on:
  workflow_dispatch:

jobs:
  fetch-roster:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm install axios cheerio

      # Run roster-fetch.js
      - name: Run roster fetch
        run: node roster-fetch.js

      # Optional: Commit roster.json back to repo
      - name: Commit roster.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add roster.json
          git commit -m "Update roster.json"
          git push
        continue-on-error: true